Added _su entries for Measurand items
COMCIFS/magnetic_dic pull request #78
Opened 2024-03-15 10:09 UTC by nautolycus

2024-03-15 11:48 UTC, vaitkus commented on cif_mag.dic
> +    _name.object_id               Cartn
```suggestion
    _name.object_id               Cartn_su
```

2024-03-15 11:48 UTC, vaitkus commented on cif_mag.dic
> +    _name.object_id               Cartn
Here and in multiple other definitions the `_name.object_id` attribute value should also contain the `_su` postfix. Otherwise we end up with the same dREL name `category_id`.`object_id` for both the Measurand and the SU data item.

2024-03-15 11:48 UTC, vaitkus commented on cif_mag.dic
> +       2024-03-15 B. McMahon: added *_su terms for Measurand quantities
The date associated with version 0.9.9 in this loop (line 5218) should also be changed to 2024-03-15.

2024-03-15 12:12 UTC, nautolycus commented on cif_mag.dic
> +    _name.object_id               Cartn
Agreed - an oversight in my script to generate these

2024-03-15 12:12 UTC, nautolycus commented on cif_mag.dic
> +       2024-03-15 B. McMahon: added *_su terms for Measurand quantities
OK - this should be fixe din the latest commit

2024-03-15 13:32 UTC, vaitkus approved these changes
Looks good to me, thank you.

Although, there is one minor thing that is done slightly differently in other dictionaries as far as the SU item definitions are concerned. Instead of repeating the same attributes in all SU definitions, these attributes are instead imported as the `general_su` save frame from the `templ_attr.cif` template file (see for example, https://github.com/COMCIFS/cif_core/blob/00815d6aa0df32560f6ecb3561e428c3e5feb29f/cif_core.dic#L5905).

Not sure if this is relevant for this dictionary though, so I will approve the PR, but I will leave it for @jamesrhester to merge it.

2024-03-15 13:37 UTC, nautolycus commented
> Looks good to me, thank you.
> 
> Although, there is one minor thing that is done slightly differently in other dictionaries as far as the SU item definitions are concerned. Instead of repeating the same attributes in all SU definitions, these attributes are instead imported as the `general_su` save frame from the `templ_attr.cif` template file (see for example, https://github.com/COMCIFS/cif_core/blob/00815d6aa0df32560f6ecb3561e428c3e5feb29f/cif_core.dic#L5905).
> 
> Not sure if this is relevant for this dictionary though, so I will approve the PR, but I will leave it for @jamesrhester to merge it.

I didn't notice this. But some of the items I have added have _type.container Matrix, so the general_su import won't apply to them.

2024-03-15 13:48 UTC, vaitkus commented
> I didn't notice this. But some of the items I have added have _type.container Matrix, so the general_su import won't apply to them.

Indeed. There were a few similar instances in the `CIF_CORE` as well which had to be handled individually.

2024-04-03 04:16 UTC, jamesrhester requested changes
I agree that we should use the `general_su` import for su data names that are not matrices, to save a little space and keep consistency. The magnetic dictionary already uses imports, so we are not introducing any more complexity either.

2024-04-03 09:20 UTC, closed without merging

2024-04-03 09:54 UTC, vaitkus commented
@nautolycus It is a bit unfortunate that you deleted the PR branch, since it was OK overall and only needed some minor tweaks to be merged (addition of some import statements). Maybe you can restore the branch via GitHub or still have a local copy on your machine that could be pushed? Or do you have some different plans, e.g. to start from scratch in a new branch?